# Generated by Django 4.2.13 on 2024-05-13 11:31

from django.db import migrations, models
import emp_details.models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_details", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_contact_no",
            field=models.BigIntegerField(
                validators=[emp_details.models.validate_contact_number]
            ),
        ),
    ]
