# Generated by Django 4.2.13 on 2024-05-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_details", "0002_alter_employee_emp_contact_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_id",
            field=models.IntegerField(unique=True),
        ),
    ]
