# Generated by Django 4.2.13 on 2024-05-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_details", "0003_alter_employee_emp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("E", "Eligible for Promotion"),
                    ("M", "Manager"),
                    ("S", "Standard"),
                ],
                max_length=1,
            ),
        ),
    ]
