# Generated by Django 5.0.6 on 2024-05-13 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emp_details', '0004_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=100)),
                ('dep_location', models.CharField(max_length=100, unique=True)),
                ('dept_id', models.IntegerField(unique=True)),
                ('man_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_details.employee', to_field='emp_id')),
            ],
        ),
    ]
