# Generated by Django 5.0.6 on 2024-05-13 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_det', '0001_initial'),
        ('emp_details', '0004_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='man_id',
            field=models.ForeignKey(limit_choices_to={'role': 'M'}, on_delete=django.db.models.deletion.CASCADE, to='emp_details.employee', to_field='emp_id'),
        ),
    ]
