# Generated by Django 4.2.13 on 2024-05-13 14:06

from django.db import migrations, models
import ems_log.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=255)),
                ("company_email", models.EmailField(max_length=254)),
                (
                    "company_contact",
                    models.BigIntegerField(
                        validators=[ems_log.models.validate_contact_number]
                    ),
                ),
                ("company_pwd", models.CharField(max_length=128)),
            ],
        ),
    ]
